import * as THREE from 'three';

/**
 * Spine-Based Geometry Generation
 * 
 * Mathematical Model:
 * The spine is a parametric 3D curve P(t) where t ∈ [0,1] represents normalized height.
 * 
 * P(t) = (x(t), y(t), z(t))
 * 
 * Components:
 * - y(t) = t × height  (linear vertical growth)
 * - x(t) = Ax × envelope(t) × oscillation_x(t)  (lateral displacement in X)
 * - z(t) = Az × envelope(t) × oscillation_z(t)  (lateral displacement in Z)
 * 
 * Envelope: sin(π×t) forces zero displacement at base (t=0) and top (t=1)
 * Oscillation: sin(ω×π×t + φ) creates S-curves when ω≥2
 * 
 * Surface is generated by sweeping a circular cross-section along the spine,
 * oriented perpendicular to the local tangent (Frenet frame).
 */

// Spine parameters - exposed to users
export interface SpineParams {
  // Enable spine-based generation
  spineEnabled: boolean;
  
  // X-axis displacement
  spineAmplitudeX: number;      // 0-50 mm: maximum lateral displacement in X
  spineFrequencyX: number;      // 0-4: number of half-periods (2 = one S-curve)
  spinePhaseX: number;          // 0-1: phase offset normalized (0-2π mapped to 0-1)
  
  // Z-axis displacement  
  spineAmplitudeZ: number;      // 0-50 mm: maximum lateral displacement in Z
  spineFrequencyZ: number;      // 0-4: number of half-periods
  spinePhaseZ: number;          // 0-1: phase offset normalized
}

// Point on the spine curve
export interface SpinePoint {
  position: THREE.Vector3;    // (x, y, z) position
  tangent: THREE.Vector3;     // Normalized tangent direction
  normal: THREE.Vector3;      // Normalized normal (perpendicular to tangent)
  binormal: THREE.Vector3;    // Normalized binormal (perpendicular to both)
}

// Default spine parameters
export const defaultSpineParams: SpineParams = {
  spineEnabled: false,
  spineAmplitudeX: 0,
  spineFrequencyX: 2,
  spinePhaseX: 0,
  spineAmplitudeZ: 0,
  spineFrequencyZ: 2,
  spinePhaseZ: 0.25,
};

/**
 * Evaluate the spine curve at parameter t
 * 
 * @param t - Normalized height (0 = base, 1 = top)
 * @param height - Total height in scene units
 * @param params - Spine parameters
 * @returns Position (x, y, z) on the spine
 */
export function evaluateSpine(
  t: number,
  height: number,
  params: SpineParams
): THREE.Vector3 {
  // Y is linear with height
  const y = t * height;
  
  // Envelope: sin(π×t) ensures zero at base and top
  const envelope = Math.sin(Math.PI * t);
  
  // X displacement: amplitude × envelope × oscillation
  const phaseX = params.spinePhaseX * Math.PI * 2;
  const oscillationX = Math.sin(params.spineFrequencyX * Math.PI * t + phaseX);
  const x = params.spineAmplitudeX * envelope * oscillationX;
  
  // Z displacement: amplitude × envelope × oscillation (independent)
  const phaseZ = params.spinePhaseZ * Math.PI * 2;
  const oscillationZ = Math.sin(params.spineFrequencyZ * Math.PI * t + phaseZ);
  const z = params.spineAmplitudeZ * envelope * oscillationZ;
  
  return new THREE.Vector3(x, y, z);
}

/**
 * Compute the tangent of the spine at parameter t (derivative of position)
 * 
 * Using central differencing for smooth C1 continuity.
 */
export function evaluateSpineTangent(
  t: number,
  height: number,
  params: SpineParams
): THREE.Vector3 {
  const epsilon = 0.001;
  const t0 = Math.max(0, t - epsilon);
  const t1 = Math.min(1, t + epsilon);
  
  const p0 = evaluateSpine(t0, height, params);
  const p1 = evaluateSpine(t1, height, params);
  
  const tangent = new THREE.Vector3().subVectors(p1, p0).normalize();
  
  // Handle edge case where tangent might be zero
  if (tangent.lengthSq() < 0.001) {
    tangent.set(0, 1, 0); // Default to up
  }
  
  return tangent;
}

/**
 * Compute the full Frenet frame (tangent, normal, binormal) at parameter t
 * 
 * The Frenet frame provides an orthonormal basis at each point on the curve:
 * - Tangent: direction of travel along curve
 * - Normal: perpendicular to tangent, points toward center of curvature
 * - Binormal: perpendicular to both (tangent × normal)
 * 
 * For cross-section placement, we use binormal and a computed perpendicular
 * rather than strict Frenet normal to avoid twisting issues.
 */
export function evaluateSpineFrame(
  t: number,
  height: number,
  params: SpineParams
): SpinePoint {
  const position = evaluateSpine(t, height, params);
  const tangent = evaluateSpineTangent(t, height, params);
  
  // Use a reference vector to compute stable normal
  // For nearly-vertical spines, we use world X as reference
  const refVector = new THREE.Vector3(1, 0, 0);
  
  // If tangent is nearly parallel to reference, use Z instead
  if (Math.abs(tangent.dot(refVector)) > 0.99) {
    refVector.set(0, 0, 1);
  }
  
  // Binormal = tangent × reference (lies in horizontal-ish plane)
  const binormal = new THREE.Vector3().crossVectors(tangent, refVector).normalize();
  
  // Normal = binormal × tangent (perpendicular to both)
  const normal = new THREE.Vector3().crossVectors(binormal, tangent).normalize();
  
  return { position, tangent, normal, binormal };
}

/**
 * Sample the spine curve at regular intervals
 * 
 * @param layerCount - Number of samples (layers)
 * @param height - Total height in scene units
 * @param params - Spine parameters
 * @returns Array of SpinePoints along the curve
 */
export function sampleSpine(
  layerCount: number,
  height: number,
  params: SpineParams
): SpinePoint[] {
  const points: SpinePoint[] = [];
  
  for (let i = 0; i <= layerCount; i++) {
    const t = i / layerCount;
    points.push(evaluateSpineFrame(t, height, params));
  }
  
  return points;
}

/**
 * Generate a circular cross-section at a spine point
 * 
 * @param frame - The Frenet frame at this point on the spine
 * @param radius - Radius of the cross-section
 * @param segments - Number of segments around the circle
 * @returns Array of 3D points forming the cross-section
 */
export function generateCrossSection(
  frame: SpinePoint,
  radius: number,
  segments: number
): THREE.Vector3[] {
  const points: THREE.Vector3[] = [];
  
  for (let j = 0; j <= segments; j++) {
    const theta = (j / segments) * Math.PI * 2;
    
    // Point on unit circle in the normal-binormal plane
    const localX = Math.cos(theta);
    const localZ = Math.sin(theta);
    
    // Transform to world space using the Frenet frame
    const worldPos = new THREE.Vector3()
      .addScaledVector(frame.normal, localX * radius)
      .addScaledVector(frame.binormal, localZ * radius)
      .add(frame.position);
    
    points.push(worldPos);
  }
  
  return points;
}

/**
 * Generate a circular cross-section with additional radial modulation
 * (for supporting the existing surface effects like wobble, ripple, etc.)
 * 
 * @param frame - The Frenet frame at this point on the spine
 * @param getRadius - Function that returns radius for a given angle theta
 * @param segments - Number of segments around the circle
 * @returns Array of 3D points forming the cross-section
 */
export function generateModulatedCrossSection(
  frame: SpinePoint,
  getRadius: (theta: number) => number,
  segments: number
): THREE.Vector3[] {
  const points: THREE.Vector3[] = [];
  
  for (let j = 0; j <= segments; j++) {
    const theta = (j / segments) * Math.PI * 2;
    const radius = getRadius(theta);
    
    // Point on circle with variable radius in the normal-binormal plane
    const localX = Math.cos(theta);
    const localZ = Math.sin(theta);
    
    // Transform to world space using the Frenet frame
    const worldPos = new THREE.Vector3()
      .addScaledVector(frame.normal, localX * radius)
      .addScaledVector(frame.binormal, localZ * radius)
      .add(frame.position);
    
    points.push(worldPos);
  }
  
  return points;
}

/**
 * Convert spine offsets to the legacy DriftOffset format for compatibility
 * This allows gradual migration while maintaining existing code paths.
 */
export interface DriftOffset {
  x: number;
  z: number;
}

export function spineToLegacyDriftOffsets(
  layerCount: number,
  height: number,
  params: SpineParams
): DriftOffset[] {
  const offsets: DriftOffset[] = [];
  
  for (let i = 0; i <= layerCount; i++) {
    const t = i / layerCount;
    const pos = evaluateSpine(t, height, params);
    offsets.push({ x: pos.x, z: pos.z });
  }
  
  return offsets;
}
