project_id = "lovable"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.create-export-payment]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false
