import { PlotterDrawing, PlotterMachine, PLOTTER_MACHINES } from '@/types/plotter';

// Generate SVG from plotter drawing
export function generateSVG(drawing: PlotterDrawing): string {
  const { paths, width, height } = drawing;
  
  // Build path data
  const pathElements = paths.map((path, index) => {
    if (path.points.length < 2) return '';
    
    const d = path.points.map((pt, i) => {
      const command = i === 0 ? 'M' : 'L';
      return `${command}${pt.x.toFixed(2)},${pt.y.toFixed(2)}`;
    }).join(' ');
    
    const color = path.color || '#000000';
    const layer = path.layer ?? 0;
    
    return `  <path d="${d}" fill="none" stroke="${color}" stroke-width="0.5" stroke-linecap="round" stroke-linejoin="round" data-layer="${layer}" />`;
  }).filter(Boolean).join('\n');
  
  const svg = `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" 
     viewBox="0 0 ${width} ${height}" 
     width="${width}mm" 
     height="${height}mm">
  <!-- Generated by Plotter Generator -->
  <g id="plotter-paths">
${pathElements}
  </g>
</svg>`;
  
  return svg;
}

// Download SVG file
export function downloadSVG(drawing: PlotterDrawing, filename: string = 'plotter-drawing.svg'): void {
  const svg = generateSVG(drawing);
  const blob = new Blob([svg], { type: 'image/svg+xml' });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

// Generate plotter G-code
export function generatePlotterGCode(
  drawing: PlotterDrawing,
  machinePreset: string = 'axidraw'
): string {
  const machine = PLOTTER_MACHINES[machinePreset] || PLOTTER_MACHINES.generic;
  const { paths } = drawing;
  
  const lines: string[] = [
    '; Plotter G-code',
    `; Machine: ${machine.name}`,
    `; Paths: ${paths.length}`,
    `; Paper size: ${drawing.width}mm x ${drawing.height}mm`,
    '',
    '; Initialization',
    'G21 ; mm units',
    'G90 ; absolute positioning',
    `G0 Z${machine.penUpZ} ; pen up`,
    `G0 F${machine.travelSpeed} ; travel speed`,
    'G0 X0 Y0 ; home',
    '',
    '; Drawing paths',
  ];
  
  for (let i = 0; i < paths.length; i++) {
    const path = paths[i];
    if (path.points.length < 2) continue;
    
    lines.push(`; Path ${i + 1}`);
    
    // Move to start (pen up)
    const start = path.points[0];
    lines.push(`G0 X${start.x.toFixed(3)} Y${start.y.toFixed(3)}`);
    
    // Pen down
    lines.push(`G0 Z${machine.penDownZ}`);
    lines.push(`G1 F${machine.drawSpeed}`);
    
    // Draw path
    for (let j = 1; j < path.points.length; j++) {
      const pt = path.points[j];
      lines.push(`G1 X${pt.x.toFixed(3)} Y${pt.y.toFixed(3)}`);
    }
    
    // Pen up
    lines.push(`G0 Z${machine.penUpZ}`);
    lines.push('');
  }
  
  lines.push('; End');
  lines.push('G0 X0 Y0 ; return home');
  lines.push('M2 ; program end');
  
  return lines.join('\n');
}

// Download G-code file
export function downloadPlotterGCode(
  drawing: PlotterDrawing,
  machinePreset: string = 'axidraw',
  filename: string = 'plotter-drawing.gcode'
): void {
  const gcode = generatePlotterGCode(drawing, machinePreset);
  const blob = new Blob([gcode], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

// Generate HPGL (for legacy plotters)
export function generateHPGL(drawing: PlotterDrawing): string {
  const lines: string[] = [
    'IN;', // Initialize
    'SP1;', // Select pen 1
  ];
  
  // HPGL uses plotter units (typically 40 units per mm)
  const scale = 40;
  
  for (const path of drawing.paths) {
    if (path.points.length < 2) continue;
    
    // Move to start
    const start = path.points[0];
    lines.push(`PU${Math.round(start.x * scale)},${Math.round(start.y * scale)};`);
    
    // Draw
    lines.push('PD;');
    for (let i = 1; i < path.points.length; i++) {
      const pt = path.points[i];
      lines.push(`PA${Math.round(pt.x * scale)},${Math.round(pt.y * scale)};`);
    }
    
    // Pen up
    lines.push('PU;');
  }
  
  lines.push('SP0;'); // Park pen
  lines.push('IN;'); // Re-initialize
  
  return lines.join('\n');
}

// Download HPGL file
export function downloadHPGL(drawing: PlotterDrawing, filename: string = 'plotter-drawing.hpgl'): void {
  const hpgl = generateHPGL(drawing);
  const blob = new Blob([hpgl], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
