import * as THREE from 'three';
import { 
  TotemStack, 
  TotemModuleConfig, 
  calculateStackHeight, 
  SPINDLE_SPECS,
  ShadeModuleConfig,
  ExtensionModuleConfig,
  SpacerModuleConfig,
  BaseModuleConfig,
  CapModuleConfig,
  PendantModuleConfig,
} from '@/types/totem';
import { generateModuleGeometry } from './module-generators';

// Get module height and diameter based on type
function getModuleInfo(module: TotemModuleConfig): { height: number; diameter: number } {
  switch (module.type) {
    case 'shade':
    case 'extension':
      const shapeModule = module as ShadeModuleConfig | ExtensionModuleConfig;
      return {
        height: shapeModule.shapeParams.height || 100,
        diameter: (shapeModule.shapeParams.topRadius || 60) * 2,
      };
    case 'spacer':
      const spacerModule = module as SpacerModuleConfig;
      return { height: spacerModule.height, diameter: spacerModule.outerDiameter };
    case 'base':
      const baseModule = module as BaseModuleConfig;
      return { height: baseModule.height, diameter: baseModule.diameter };
    case 'cap':
      const capModule = module as CapModuleConfig;
      return { 
        height: capModule.domeHeight + capModule.bottomInterface.ring.height,
        diameter: capModule.bottomInterface.ring.outerDiameter,
      };
    case 'pendant':
      const pendantModule = module as PendantModuleConfig;
      return { height: pendantModule.canopyHeight, diameter: pendantModule.canopyDiameter };
    default:
      return { height: 50, diameter: 50 };
  }
}

/**
 * Convert geometry to STL binary format
 */
function geometryToSTLBinary(geometry: THREE.BufferGeometry): ArrayBuffer {
  const positions = geometry.getAttribute('position');
  const indices = geometry.getIndex();
  
  let triangleCount: number;
  if (indices) {
    triangleCount = indices.count / 3;
  } else {
    triangleCount = positions.count / 3;
  }
  
  // STL binary format: 80 byte header + 4 byte triangle count + (50 bytes per triangle)
  const bufferLength = 80 + 4 + (triangleCount * 50);
  const buffer = new ArrayBuffer(bufferLength);
  const dataView = new DataView(buffer);
  
  // Write header (80 bytes)
  const header = 'Totem Module - Generated by P3D Gen';
  for (let i = 0; i < 80; i++) {
    dataView.setUint8(i, i < header.length ? header.charCodeAt(i) : 0);
  }
  
  // Write triangle count
  dataView.setUint32(80, triangleCount, true);
  
  // Write triangles
  let offset = 84;
  const cb = new THREE.Vector3();
  const ab = new THREE.Vector3();
  
  for (let i = 0; i < triangleCount; i++) {
    let a: number, b: number, c: number;
    
    if (indices) {
      a = indices.getX(i * 3);
      b = indices.getX(i * 3 + 1);
      c = indices.getX(i * 3 + 2);
    } else {
      a = i * 3;
      b = i * 3 + 1;
      c = i * 3 + 2;
    }
    
    // Get vertices
    const vA = new THREE.Vector3(
      positions.getX(a),
      positions.getY(a),
      positions.getZ(a)
    );
    const vB = new THREE.Vector3(
      positions.getX(b),
      positions.getY(b),
      positions.getZ(b)
    );
    const vC = new THREE.Vector3(
      positions.getX(c),
      positions.getY(c),
      positions.getZ(c)
    );
    
    // Calculate normal
    cb.subVectors(vC, vB);
    ab.subVectors(vA, vB);
    cb.cross(ab);
    cb.normalize();
    
    // Write normal
    dataView.setFloat32(offset, cb.x, true); offset += 4;
    dataView.setFloat32(offset, cb.y, true); offset += 4;
    dataView.setFloat32(offset, cb.z, true); offset += 4;
    
    // Write vertices (geometry is already in mm for totem)
    dataView.setFloat32(offset, vA.x, true); offset += 4;
    dataView.setFloat32(offset, vA.y, true); offset += 4;
    dataView.setFloat32(offset, vA.z, true); offset += 4;
    
    dataView.setFloat32(offset, vB.x, true); offset += 4;
    dataView.setFloat32(offset, vB.y, true); offset += 4;
    dataView.setFloat32(offset, vB.z, true); offset += 4;
    
    dataView.setFloat32(offset, vC.x, true); offset += 4;
    dataView.setFloat32(offset, vC.y, true); offset += 4;
    dataView.setFloat32(offset, vC.z, true); offset += 4;
    
    // Attribute byte count (unused)
    dataView.setUint16(offset, 0, true); offset += 2;
  }
  
  return buffer;
}

/**
 * Download a single totem module as STL
 */
export function downloadTotemModuleSTL(config: TotemModuleConfig, filename?: string): void {
  const geometry = generateModuleGeometry(config, false); // scale = false to keep in mm
  const stlBuffer = geometryToSTLBinary(geometry);
  
  const blob = new Blob([stlBuffer], { type: 'application/octet-stream' });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement('a');
  link.href = url;
  link.download = filename || `totem-${config.type}-${config.id}.stl`;
  link.click();
  
  URL.revokeObjectURL(url);
  geometry.dispose();
}

/**
 * Download all modules in a stack as separate STL files
 */
export function downloadTotemStackSTLs(stack: TotemStack): void {
  stack.modules.forEach((module, index) => {
    const paddedIndex = String(index + 1).padStart(2, '0');
    const filename = `totem-${paddedIndex}-${module.type}.stl`;
    downloadTotemModuleSTL(module, filename);
  });
}

/**
 * Generate assembly instructions as a text file
 */
export function downloadAssemblyGuide(stack: TotemStack): void {
  const spindleSpec = SPINDLE_SPECS[stack.spindleSize];
  const totalHeight = calculateStackHeight(stack.modules);
  const recommendedSpindleLength = totalHeight + 20;
  
  let guide = `TOTEM LAMP ASSEMBLY GUIDE
========================

Generated by P3D Gen

SPINDLE REQUIREMENTS
--------------------
Diameter: ${spindleSpec.diameter}mm wooden dowel
Recommended Length: ${recommendedSpindleLength}mm
Hole Diameter in Modules: ${spindleSpec.holeDiameter}mm (includes ${spindleSpec.holeDiameter - spindleSpec.diameter}mm clearance)

STACK ORDER (Bottom to Top)
----------------------------
`;

  stack.modules.forEach((module, index) => {
    const info = getModuleInfo(module);
    guide += `${index + 1}. ${module.name} (${module.type.toUpperCase()}) - ${info.height}mm tall, ${info.diameter}mm diameter\n`;
  });

  guide += `
TOTAL STACK HEIGHT: ${totalHeight}mm

ASSEMBLY INSTRUCTIONS
---------------------
1. Print all modules with the flat side down
2. Cut wooden dowel to ${recommendedSpindleLength}mm
3. Sand dowel lightly for smooth fit
4. Stack modules from bottom to top as listed above
5. Insert spindle through all modules
6. For table lamps: Add weight to base cavity before closing

PRINTING RECOMMENDATIONS
------------------------
- Layer Height: 0.2mm
- Infill: 15-20%
- Supports: Not required if printed flat side down
- Material: PLA or PETG recommended

---
Generated by P3D Gen Totem Builder
`;

  const blob = new Blob([guide], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement('a');
  link.href = url;
  link.download = 'totem-assembly-guide.txt';
  link.click();
  
  URL.revokeObjectURL(url);
}

/**
 * Download complete totem package (all STLs + assembly guide)
 */
export function downloadTotemPackage(stack: TotemStack): void {
  // Download all STLs
  downloadTotemStackSTLs(stack);
  
  // Download assembly guide
  setTimeout(() => {
    downloadAssemblyGuide(stack);
  }, 500);
}
